### ISSUE TITLE
Baseline Questionnaire 2023 - Spoorthi Form - Replace drop down values with values in excel sheet

### ISSUE THREAD

**Issue by Shravan333333** [NikithaVijayanand/BuzzStaff#44]
![Image](https://github.com/user-attachments/assets/cb72a335-c855-4318-980c-2f04d1d6b6e0)

![Image](https://github.com/user-attachments/assets/27d83c1f-e638-40cf-aa68-c710fe328451)

**Comment by meshreyes123** [comment]
Fixed

**Comment by Shravan333333** [comment]
Fixed. Working fine after QA verification so closing this issue
