### ISSUE TITLE
View Bugs - List below - Spoorthi View Form - Sr. Operations Manager

### ISSUE THREAD

**Issue by Shravan333333** [NikithaVijayanand/BuzzStaff#62]
![Image](https://github.com/user-attachments/assets/3171ae98-50d6-4a29-90d9-e41912114ac0)

![Image](https://github.com/user-attachments/assets/ecfff273-64af-4904-9662-9b4c9968779e)

![Image](https://github.com/user-attachments/assets/78bb92d0-48ea-449a-aa55-4a51b7a2259e)

![Image](https://github.com/user-attachments/assets/715c8e26-ca86-42f7-9c57-6c0669e9fe2c)

![Image](https://github.com/user-attachments/assets/d0822762-43b8-4a5c-a7a8-f9a0e81bcef4)

![Image](https://github.com/user-attachments/assets/3b6539bf-b6ca-41c9-8bf4-4183d10c37db)

**Comment by meshreyes123** [comment]
fixed

**Comment by meshreyes123** [comment]
fixed

**Comment by Shravan333333** [comment]
Fixed. Working fine after QA verification so closing this issue
